name: 'Cleanup Runner'
description: 'Aggressively clean up runner to free disk space'
runs:
  using: "composite"
  steps:
    - name: Aggressive cleanup
      shell: bash
      run: |
        echo "Initial disk usage:"
        df -h

        # Remove Java (JDKs)
        sudo rm -rf /usr/lib/jvm


        # Remove Swift toolchain
        sudo rm -rf /usr/share/swift

        # Remove Haskell (GHC)
        sudo rm -rf /usr/local/.ghcup


        # Remove Android SDKs
        sudo rm -rf /usr/local/lib/android

        # Remove Chromium (optional if not using for browser tests)
        sudo rm -rf /usr/local/share/chromium

        # Remove Microsoft/Edge and Google Chrome builds
        sudo rm -rf /opt/microsoft /opt/google




        echo "Final disk usage:"
        df -h